apiVersion: v1
kind: ConfigMap
metadata:
  name: chimera-scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    profiles:
    - schedulerName: chimera-scheduler
      plugins:
        score:
          enabled:
          - name: NodeResourcesBalancedAllocation
            weight: 2
          - name: NodeResourcesFit
            weight: 3
          - name: NodeAffinity
            weight: 5
          - name: PodTopologySpread
            weight: 4
      pluginConfig:
      - name: NodeResourcesFit
        args:
          scoringStrategy:
            type: MostAllocated
            resources:
            - name: cpu
              weight: 1
            - name: memory
              weight: 1
            - name: nvidia.com/gpu
              weight: 10
      - name: PodTopologySpread
        args:
          defaultingType: System
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chimera-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: chimera-scheduler
  template:
    metadata:
      labels:
        component: chimera-scheduler
    spec:
      containers:
      - name: kube-scheduler
        image: k8s.gcr.io/kube-scheduler:v1.22.0
        args:
          - kube-scheduler
          - --config=/etc/kubernetes/scheduler-config.yaml
          - --v=3
        volumeMounts:
          - name: config
            mountPath: /etc/kubernetes/
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: chimera-scheduler-config
