apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: realtime-inference
value: 1000000
globalDefault: false
description: "This priority class is for real-time inference workloads"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: batch-inference
value: 500000
globalDefault: false
description: "This priority class is for batch inference workloads"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: spot-batch-inference
value: 100000
globalDefault: false
description: "This priority class is for batch inference workloads on spot instances"
